### ISSUE TITLE
GTFS containing non-ascii characters in txt files fails to load

### ISSUE THREAD

**Issue by miles-grant-ibigroup** [OpenTransitTools/transitcast#1]
The table below shows the first few bytes of a `calendar.txt` file that currently fails to import. The `indexOf` method on line 191 of `gtfs_file_parser.go` fails to match these strings, as they are not the same. 

I'm not sure if byte order marks are allowed in GTFS, but this happened to me with a few different feeds, so it might be something we want to address. My quick fix was to replace the `==` with 2 checks to see if one of the strings contains each other, but I think a cleaner fix would be preferred.

hex | rendered
-- | --
73 65 72 76 69 63 65 5f 69 64 | service_id
ef bb bf 73 65 72 76 69 63 65 5f 69 64 | service_id

**Comment by miles-grant-ibigroup** [comment]
Here is an example of a GTFS feed with a byte order mark in its `calendar.txt`: [http://nycferry.connexionz.net/rtt/public/utility/gtfs.aspx](http://nycferry.connexionz.net/rtt/public/utility/gtfs.aspx)

Here is the error that is thrown: 
```
GTFS_LOADER : 2022/05/11 13:13:00.091562 main.go:96: main: Database Stopping : 0.0.0.0
GTFS_LOADER : 2022/05/11 13:13:00.094063 main.go:107: main: Completed
GTFS_LOADER : 2022/05/11 13:13:00.094086 main.go:19: main: error: in file stop_times.txt, line 2: [unable to find header: shape_dist_traveled in file stop_times.txt, line 2: [unable to find header: shape_dist_traveled]]
```

**Comment by gaetano7** [comment]
Added check for byte order mark when parsing headers of each csv file.
