### ISSUE TITLE
`calendar_dates.txt` file

### ISSUE THREAD

**Issue by miles-grant-ibigroup** [OpenTransitTools/transitcast#2]
This is an optional file in the GTFS spec, and it is optional within transitcast as well. Supplying an empty file (with only the headers) leads to everything working as expected. However, if the file is missing, the system crashes.

If I missed something and the file is somehow required to have some info in it we should add a warning. Otherwise, we should interpret the file missing the same as the file containing no rows.

**Comment by gaetano7** [comment]
Allowed for a missing calendar.txt file so long as calendar_dates.txt is present. Issue warning about possibly missing trip deviations when calendar.txt file isn't present, as its currently used to load trips that are relevant to future predictions.
