### ISSUE TITLE
TripUpdates: Some Updates Contain Same `stop_sequence` Repeatedly 

### ISSUE THREAD

**Issue by miles-grant-ibigroup** [OpenTransitTools/transitcast#5]
We've observed some stray TripUpdates being published that contain invalid `stop_sequence` lists. The number of stops seems to be aligned with an actual trip, but each `stop_sequence` is the same number, and sometimes an invalid one. The list of stop sequences looks something like this: `[17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17]`. 

I can provide specific `trip_id`s if this is helpful. 

I'm not sure where the culprit is. Either in https://github.com/OpenTransitTools/transitcast/blob/c0d9286fed2107a201a53970ac70836ccba0db9f/app/gtfs-aggregator/aggregator/prediction_publisher.go#L185 `toStop` contains incorrect data, or the method itself is being called incorrectly. 

I should note that these erroneous trips are appearing in addition to valid data, so the issue is not urgent.

**Comment by gaetano7** [comment]
A tripID and time would be helpful to track it down. If not available I could monitor it.

**Comment by miles-grant-ibigroup** [comment]
At unix timestamp 1664366384 I'm noticing it in trip ids `11844969`, `11829788`, among others. It seems to only affect the `pb` and `text` output. `json` works fine.

**Comment by gaetano7** [comment]
You should find the issue is resolved. Please verify on your end.

**Comment by miles-grant-ibigroup** [comment]
Yep things are correct for me now thanks so much!
